// <auto-generated />
using System;
using HenBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HenBot.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230823213037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("HenBot.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Limit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SavedChats");
                });

            modelBuilder.Entity("HenBot.TagQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SavedChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SavedChatId");

                    b.ToTable("TagQuery");
                });

            modelBuilder.Entity("HenBot.TagQuery", b =>
                {
                    b.HasOne("HenBot.Chat", "Chat")
                        .WithMany("SavedTags")
                        .HasForeignKey("SavedChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("HenBot.Chat", b =>
                {
                    b.Navigation("SavedTags");
                });
#pragma warning restore 612, 618
        }
    }
}
